sudo: false
dist: trusty
language: python
python:
  - "3.6"
cache: pip

before_install:
  - rm -rf public || exit 0
install:
  - pip install pygments awscli
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo -v

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: propersquid.com
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: scott-wilson/propersquid.com
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
