sudo: required

language: ruby
rvm:
  - 2.1

before_install:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs
  - git lfs install
  # Workaround for git lfs not getting Travis' screen width.
  - git lfs pull > /tmp/git-lfs-pull.log
  - cat /tmp/git-lfs-pull.log

before_script:
 - chmod +x ./script/cibuild.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild.sh

after_success: bundle exec s3_website push

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
