# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Propersquid
name: Scott Wilson
email: scott@propersquid.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website for animation, coding, games, and VFX related projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://propersquid.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: propersquid
github_username:  scott-wilson
stackoverflow_username:  3108288/scottwilson
timezone: America/Vancouver

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
