# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Propersquid
email: scott@propersquid.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website for animation, coding, games, and VFX related projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://propersquid.com.s3.amazonaws.com.s3-website-us-east-1.amazonaws.com/" # the base hostname & protocol for your site
twitter_username: propersquid
github_username:  scott-wilson
stackoverflow_username:  3108288/scottwilson

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables
    - autolink
    - with_toc_data

exclude: [vendor]
