baseURL = "https://propersquid.com"
languageCode = "en-us"
title = "Propersquid"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Scott Wilson"
    description = "Personal blog powered by Hugo"
    githubUsername = "scott-wilson"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "c++", "rust"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

[[menu.main]]
    url = "/resume/"
    name = "Resume"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:scott@propersquid.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/scott-wilson/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/propersquid/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/scott-wilson-9876a767/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/3108288/scottwilson/"
    name = "stack-overflow"
    weight = 5
